schema = 3

[mod]
  [mod.'github.com/amarbel-llc/go-lib-mcp']
    version = 'v0.0.0-20260215160001-e634f96c4717'
    hash = 'sha256-DiqonnNwZdI7TaYKUlgmS3DsjOxWpVtiMmXVmwD5nwQ='

  [mod.'github.com/amarbel-llc/purse-first']
    version = 'v0.0.0-20260215231605-c80c31bd93b5'
    hash = 'sha256-uabpaEw+uixwgFel4FDQajhQdcHUfIC9mbUQ5y8HSEQ='

  [mod.'github.com/amarbel-llc/purse-first/libs/go-mcp']
    version = 'v0.0.0-20260217222858-cd512e5ef8b7'
    hash = 'sha256-S7j8n/4sc6fDWFBnpbNJqfx4LgN+X0fT4eaTT2Ex2DY='
